# Generated by Django 5.2 on 2025-04-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_token_date_token_redeemed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='date',
        ),
    ]
